PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Blogs;
DROP TABLE IF EXISTS BlogTags;
DROP TABLE IF EXISTS BlogsToTags;

COMMIT;

BEGIN TRANSACTION;

CREATE TABLE Authors (
	
	ID INTEGER NOT NULL PRIMARY KEY,
	SSOID TEXT NULL,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	Email TEXT NULL,
	Active INTEGER NOT NULL DEFAULT 1,
	CreateDate TEXT NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE Blogs (
	
	ID INTEGER NOT NULL PRIMARY KEY,
	Title TEXT NOT NULL,
	Subtitle TEXT NULL,
	Content TEXT NULL,
	ImagePath TEXT NULL,
    ImageThumbnailPath TEXT NULL,
    Slug TEXT NOT NULL,
	PublishDate TEXT NULL,
	AuthorID INTEGER NOT NULL,
	Active INTEGER NOT NULL DEFAULT 1,
	CreateDate TEXT NOT NULL DEFAULT CURRENT_DATE,
	
	FOREIGN KEY (AuthorID) REFERENCES Authors(ID)
	
);

CREATE TABLE [BlogTags] (
	
	[ID] INTEGER NOT NULL PRIMARY KEY,
	[Name] TEXT NOT NULL,
	[Active] INTEGER NOT NULL DEFAULT 1,
	[CreateDate] TEXT NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE [BlogsToTags] (
	
	[ID] INTEGER NOT NULL PRIMARY KEY,
	[BlogID] INTEGER NOT NULL,
	[BlogTagID] TEXT NOT NULL,
	
	FOREIGN KEY (BlogID) REFERENCES Blogs(ID),
	FOREIGN KEY (BlogTagID) REFERENCES BlogTags(ID)
);

COMMIT;