PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Visits;

COMMIT;

BEGIN TRANSACTION;

CREATE TABLE Visits (
	
	[ID] INTEGER NOT NULL PRIMARY KEY,
	
	[Date] TEXT NOT NULL,
	[UserAgent] TEXT NULL,
	[Domain] TEXT NULL,
	[Page] TEXT NULL,
	[Referer] TEXT NULL,
	[OS] TEXT NULL,
	[Device] TEXT NULL,

	[Active] INTEGER NOT NULL DEFAULT 1,
	[CreateDate] TEXT NOT NULL DEFAULT CURRENT_DATE
);

COMMIT;